{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "37d0b8b9-0b21-4a43-bb36-dbec9f23c022",
   "metadata": {},
   "source": [
    "교수님꺼"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "8f639f30-2265-4812-b4f4-edceec06084f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from dash import html, dcc, Input, Output, State, Dash\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from sqlalchemy import text, create_engine\n",
    "import pymysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "88fd5224-e8b3-47ac-95a9-1a67a7eb4b75",
   "metadata": {},
   "outputs": [],
   "source": [
    "pro = \"mysql+pymysql://\"\n",
    "user = \"bigdata\"\n",
    "password = \"Bigdata123!!\"\n",
    "host = \"192.168.56.101\"\n",
    "port = '3306'\n",
    "db = 'SampleDB'\n",
    "engine = create_engine(f'{pro}{user}:{password}@{host}:{port}/{db}')\n",
    "conn = engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "e05296af-8ebe-4bc6-8f08-01c9c4a9c3e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "continent = pd.read_sql('select distinct continent from world',conn)\n",
    "continent_options = [{\"label\":list(i)[0],\"value\":list(i)[0]} for i in continent.values]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "id": "31a47999-9596-4756-89a6-674895b223bb",
   "metadata": {},
   "outputs": [],
   "source": [
    "app = Dash(__name__)\n",
    "app.layout = html.Div(\n",
    "    [\n",
    "        html.Label(\"대륙\"),\n",
    "        dcc.Dropdown(id=\"dropdown1\",\n",
    "                     options = continent_options),\n",
    "        html.Label('국가'),\n",
    "        html.Div(id=\"output-dropdown\"),\n",
    "        dcc.RadioItems(id=\"radio-items\",\n",
    "                       options = ['파이그래프','막대그래프','라인그래프'], \n",
    "                       value = \"막대그래프\",\n",
    "                       inline = True),\n",
    "        html.Hr(),\n",
    "        html.Div(id=\"output-country\")\n",
    "    ]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "7900a51f-544d-4f58-87f3-2c858ecba2e2",
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.callback(\n",
    "    Output('output-dropdown','children'),\n",
    "    Input(\"dropdown1\",'value')\n",
    "    \n",
    ")\n",
    "def updata_country_dropdown(continent):\n",
    "    country = pd.read_sql(f\"select distinct country from world where continent = '{continent}'\",conn)\n",
    "    country_options = [{\"label\":list(i)[0],\"value\":list(i)[0]} for i in country.values]\n",
    "    return html.Div(\n",
    "        [\n",
    "            dcc.Dropdown(\n",
    "                id=\"dropdown2\",\n",
    "                options = country_options\n",
    "            )         \n",
    "        ]    \n",
    "    )\n",
    "@app.callback(\n",
    "    Output(\"output-country\",\"children\"),\n",
    "    Input('dropdown1','value'),\n",
    "    Input('dropdown2','value'),\n",
    ")\n",
    "def update_country(x1,x2):\n",
    "    data = pd.read_sql(f\"select year,pop from world where country = '{x2}'\",conn)\n",
    "    pop_data = pd.read_sql(f\"select country, pop from world where pop = (select max(pop) from world where continent = '{x1}')\",conn)\n",
    "    \n",
    "    continent_population = pd.read_sql(f\"select pop, country from world where continent = '{x1}' and year = 2007\",conn)\n",
    "    continent_country = continent_population.loc[:,\"country\"]\n",
    "    continent_pop = continent_population.loc[:,\"pop\"]\n",
    "    colors = [\"Gray\"]*len(continent_population)\n",
    "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
    "    colors[continent_pop.sort_values(ascending=False).index[1]] = \"Blue\"\n",
    "    country_name = pop_data.loc[:,\"country\"][0]\n",
    "    pop = pop_data.loc[:,\"pop\"][0]\n",
    "    \n",
    "    fig = go.Figure([go.Bar(x=continent_country.values,y=continent_pop.values,marker_color=colors)])\n",
    "    fig1 = px.bar(data,x='year',y='pop')\n",
    "    fig2 = px.line(data,x='year',y='pop')\n",
    "    fig3 = px.pie(data,values=\"pop\",names=\"year\")\n",
    "    return html.Div([\n",
    "        html.Div(f'{x1}대륙에서 인구가 가장 많은 나라는 {country_name}이고 인구수 {pop}니다.'),\n",
    "        dcc.Graph(figure = fig),\n",
    "        html.Div(f'{x1}대륙의 {x2}나라의 년도별 인구수 그래프입니다.'),\n",
    "        html.Hr(),\n",
    "        dcc.Graph(id=\"bar-graph\",\n",
    "                  figure = fig1),\n",
    "        dcc.Graph(id=\"line-graph\",\n",
    "                  figure = fig2),\n",
    "        dcc.Graph(id=\"pie-graph\",\n",
    "                  figure = fig3)\n",
    "    ])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "id": "82591b54-e6dc-4aba-9e88-79109907a8b3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      "Dash is running on http://192.168.56.101:7777/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://192.168.56.101:7777/ (Press CTRL+C to quit)\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"GET / HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/flask/app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/dash.py\", line 1344, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/tmp/ipykernel_3830/2177713276.py\", line 30, in update_country\n",
      "    colors[continent_pop[continent_pop == continent_pop.max()].index[0]] = \"Crimson\"\n",
      "  File \"/home/isaac/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py\", line 4604, in __getitem__\n",
      "    return getitem(key)\n",
      "IndexError: index 0 is out of bounds for axis 0 with size 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "192.168.56.1 - - [21/Feb/2022 15:29:22] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:24] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:24] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:27] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "192.168.56.1 - - [21/Feb/2022 15:29:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "app.run_server(host=host,port=\"7777\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eee40ab7-98db-48a5-a617-e2b2e973a2e1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
